### ISSUE TITLE
Deploy latest changes to npm

### ISSUE THREAD

**Issue by HaNdTriX** [evanshortiss/html5-fs#1]
https://github.com/evanshortiss/html5-fs/commit/2e9e8538a5c81d391fd1c3b9f20ca0ebcb18c116

**Comment by evanshortiss** [comment]
Sure, could include #2 as part of this @HaNdTriX

**Comment by evanshortiss** [comment]
@HaNdTriX I've deployed the requested changes as version 0.1.0. Hope this is helpful, and apologies for the delays 😄

**Comment by HaNdTriX** [comment]
Thanks @evanshortiss !
